/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'
import { Route as ServicesSeoMarketingRouteImport } from './routes/services.seo-marketing'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services.mobile-app-development'
import { Route as ServicesCompletePartnershipRouteImport } from './routes/services.complete-partnership'
import { Route as ServicesAiAutomationRouteImport } from './routes/services.ai-automation'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/website-development',
    path: '/website-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSeoMarketingRoute = ServicesSeoMarketingRouteImport.update({
  id: '/seo-marketing',
  path: '/seo-marketing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/mobile-app-development',
    path: '/mobile-app-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCompletePartnershipRoute =
  ServicesCompletePartnershipRouteImport.update({
    id: '/complete-partnership',
    path: '/complete-partnership',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAiAutomationRoute = ServicesAiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/complete-partnership': typeof ServicesCompletePartnershipRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/seo-marketing': typeof ServicesSeoMarketingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/complete-partnership': typeof ServicesCompletePartnershipRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/seo-marketing': typeof ServicesSeoMarketingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/complete-partnership': typeof ServicesCompletePartnershipRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/seo-marketing': typeof ServicesSeoMarketingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/services/ai-automation'
    | '/services/complete-partnership'
    | '/services/mobile-app-development'
    | '/services/seo-marketing'
    | '/services/website-development'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/sitemap.xml'
    | '/api/chat'
    | '/services/ai-automation'
    | '/services/complete-partnership'
    | '/services/mobile-app-development'
    | '/services/seo-marketing'
    | '/services/website-development'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/services/ai-automation'
    | '/services/complete-partnership'
    | '/services/mobile-app-development'
    | '/services/seo-marketing'
    | '/services/website-development'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo-marketing': {
      id: '/services/seo-marketing'
      path: '/seo-marketing'
      fullPath: '/services/seo-marketing'
      preLoaderRoute: typeof ServicesSeoMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/complete-partnership': {
      id: '/services/complete-partnership'
      path: '/complete-partnership'
      fullPath: '/services/complete-partnership'
      preLoaderRoute: typeof ServicesCompletePartnershipRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-automation': {
      id: '/services/ai-automation'
      path: '/ai-automation'
      fullPath: '/services/ai-automation'
      preLoaderRoute: typeof ServicesAiAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAiAutomationRoute: typeof ServicesAiAutomationRoute
  ServicesCompletePartnershipRoute: typeof ServicesCompletePartnershipRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesSeoMarketingRoute: typeof ServicesSeoMarketingRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiAutomationRoute: ServicesAiAutomationRoute,
  ServicesCompletePartnershipRoute: ServicesCompletePartnershipRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesSeoMarketingRoute: ServicesSeoMarketingRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
